#!/bin/bash
# Test script for Profile Section Fixes
# Run this to verify all profile functionality works correctly

echo "=== Profile Section Testing Guide ==="
echo ""
echo "MANUAL RESTART REQUIRED:"
echo "If npm run dev fails with lock file error, please:"
echo "1. Open PowerShell as Administrator"
echo "2. Run: Get-Process node | Stop-Process -Force"
echo "3. Delete the lock file at: qtsr-app/.next/dev/lock"
echo "4. Run: npm run dev"
echo ""
echo "=== Test Cases ==="
echo ""

echo "TEST 1: SESSION CREATION AND TRACKING"
echo "-----------------------------------"
echo "Steps:"
echo "1. Navigate to http://localhost:3000/login"
echo "2. Sign up with a new email"
echo "3. After signup, go to Dashboard"
echo "4. Click on your profile (top right)"
echo "5. Go to Profile page"
echo "6. Click 'Activity' tab"
echo ""
echo "Expected Results:"
echo "✓ 'Active Sessions' section shows 1 session"
echo "✓ Session shows real device info (e.g., 'Windows Device - Chrome')"
echo "✓ Session shows real IP address (NOT '0.0.0.0')"
echo "✓ Session shows real location (e.g., 'City, Country')"
echo "✓ 'Login History' shows 1 LOGIN event"
echo "✓ Event shows same real IP and location"
echo ""

echo "TEST 2: LOGIN HISTORY TRACKING"
echo "-----------------------------"
echo "Steps:"
echo "1. Go back to Dashboard"
echo "2. Click Sign Out"
echo "3. Sign in again with same email"
echo "4. Go to Profile → Activity tab"
echo ""
echo "Expected Results:"
echo "✓ 'Active Sessions' shows 1 session"
echo "✓ 'Login History' now shows 2 LOGIN events"
echo "✓ Both events have real IP and location"
echo "✓ Timestamps are correct (most recent first)"
echo ""

echo "TEST 3: MULTIPLE SESSIONS"
echo "------------------------"
echo "Steps:"
echo "1. Keep current browser logged in"
echo "2. Open another browser (or incognito window)"
echo "3. Log in to the same account"
echo "4. Go to Profile → Activity tab in second browser"
echo ""
echo "Expected Results:"
echo "✓ 'Active Sessions' shows 2 sessions"
echo "✓ One marked as 'CURRENT'"
echo "✓ Other shows 'LOGOUT' button"
echo "✓ Different device info for different browsers"
echo ""

echo "TEST 4: SESSION LOGOUT"
echo "---------------------"
echo "Steps:"
echo "1. In the second browser, click 'LOGOUT' on the first session"
echo ""
echo "Expected Results:"
echo "✓ First session is removed from the list"
echo "✓ Only current session remains"
echo "✓ First browser should still be logged in (cached)"
echo ""

echo "TEST 5: PASSWORD CHANGE LOGGING"
echo "-------------------------------"
echo "Steps:"
echo "1. Go to Profile → Profile tab"
echo "2. Click 'CHANGE PASSWORD'"
echo "3. Enter current and new password"
echo "4. Click CHANGE"
echo "5. Go to Profile → Security tab (or Activity tab)"
echo ""
echo "Expected Results:"
echo "✓ Success message appears"
echo "✓ 'Recent Security Events' shows 'PASSWORD CHANGED'"
echo "✓ Event shows real IP and location"
echo "✓ Timestamp is recent"
echo ""

echo "TEST 6: 2FA ENABLE/DISABLE"
echo "-------------------------"
echo "Steps:"
echo "1. Go to Profile → Security tab"
echo "2. Click 'ENABLE 2FA'"
echo "3. Backup codes modal appears (save them)"
echo "4. Close the modal"
echo "5. Go to Activity tab"
echo ""
echo "Expected Results:"
echo "✓ 2FA status changes to 'ENABLED' in green"
echo "✓ 'Recent Security Events' shows '2FA ENABLED'"
echo "✓ Event has real IP and location"
echo ""

echo "TEST 7: 2FA DISABLE"
echo "------------------"
echo "Steps:"
echo "1. Go back to Security tab"
echo "2. Click 'DISABLE 2FA'"
echo "3. Confirm the action"
echo "4. Go to Activity tab"
echo ""
echo "Expected Results:"
echo "✓ 2FA status changes to 'DISABLED' in red"
echo "✓ 'Recent Security Events' shows '2FA DISABLED'"
echo "✓ Event has real IP and location"
echo ""

echo "TEST 8: LOGOUT ALL DEVICES"
echo "-------------------------"
echo "Steps:"
echo "1. If you have multiple sessions, go to Activity tab"
echo "2. Click 'LOGOUT ALL DEVICES' button"
echo ""
echo "Expected Results:"
echo "✓ Redirected to login page"
echo "✓ All sessions are terminated"
echo "✓ Need to log in again"
echo ""

echo "=== VERIFICATION CHECKLIST ==="
echo ""
echo "Check the console (F12 → Console) for any error messages:"
echo "✓ No 'Geolocation API failed' errors"
echo "✓ Look for [PROFILE], [LOGIN], [GEO] prefixed log messages"
echo "✓ No auth or permission errors"
echo ""

echo "=== COMMON ISSUES ==="
echo ""
echo "1. No sessions showing:"
echo "   - Check browser console for errors"
echo "   - Verify .env.local has Firebase credentials"
echo "   - Check Firebase DB rules are deployed"
echo ""
echo "2. Sessions show '0.0.0.0' IP:"
echo "   - This means geolocation API failed"
echo "   - Check network connectivity"
echo "   - Verify API endpoints are accessible"
echo ""
echo "3. Data not refreshing:"
echo "   - Hard refresh browser (Ctrl+Shift+R)"
echo "   - Clear local storage"
echo ""

echo "=== TESTING COMPLETE ==="
echo ""
echo "If all tests pass, profile section is fully functional!"
